# Changes here will be overwritten by Copier
_commit: v0.0.63-1-g3d9cd7a
_src_path: gh:LabAutomationAndScreening/copier-python-package-template
configure_python_asyncio: false
configure_vcrpy: false
create_docs: false
description: Library for facilitating easy deployment of ephemeral pulumi stacks
full_repo_url: https://github.com/LabAutomationAndScreening/ephemeral-pulumi-deploy
install_aws_ssm_port_forwarding_plugin: false
install_claude_cli: true
is_frozen_executable: false
is_open_source: true
package_name: ephemeral-pulumi-deploy
primary_author: Eli Fine
pull_from_ecr: false
python_ci_versions:
- 3.12.7
- 3.13.9
- 3.14.0
python_package_registry: PyPI
python_version: 3.12.7
repo_name: ephemeral-pulumi-deploy
repo_org_name: LabAutomationAndScreening
ssh_port_number: 54296
use_codecov: true
use_windows_in_ci: false
use_windows_in_exe_ci: false

