# Changes here will be overwritten by Copier
_commit: v0.0.5-2-gf12fffe
_src_path: gh:LabAutomationAndScreening/copier-python-package-template
create_docs: false
description: Library for facilitating easy deployment of ephemeral pulumi stacks
full_repo_url: https://github.com/LabAutomationAndScreening/ephemeral-pulumi-deploy
package_name: ephemeral-pulumi-deploy
primary_author: Eli Fine
python_ci_versions:
- 3.12.7
- 3.13.1
python_version: 3.12.7
repo_name: ephemeral-pulumi-deploy
ssh_port_number: 54296
use_windows_in_ci: false

