version: '3.8'
services:
  devcontainer:
    build:
      context: .
      args:
        REPO_NAME: ephemeral-pulumi-deploy
    # You can run `devcontainer-info content-url` in codespaces to see what image base is
    volumes:
      - ..:/workspaces/ephemeral-pulumi-deploy:cached
      # Break out the venv folder as a separate docker volume for better performance on Windows hosts
      - python_venv:/workspaces/ephemeral-pulumi-deploy/.venv
    command: sleep infinity
    ports:
      - "54296:2222"
    environment:
      - AWS_PROFILE=localstack


volumes:
  python_venv: {}
